name: Security Checks

on:
  pull_request:                # Runs on pull requests
  schedule:                    # Runs every week
    - cron: '0 0 * * 0'        # Weekly on Sunday at midnight

permissions:
  contents: read               # Required to clone the repo
  security-events: write       # Required for CodeQL to upload results
  id-token: write              # Optional: Enables OpenID Connect (OIDC) token issuance for secure operations

jobs:
  security_scans:
    name: Security Scans
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched for scanning

      # Step 2: Run Static Application Security Testing (SAST) with CodeQL
      - name: Initialize CodeQL for SAST
        uses: github/codeql-action/init@v3
        with:
          languages: python
          queries: ./  # Explicitly point to the repository code for custom queries (if needed)
      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          output: ./codeql-results.sarif  # Save results locally for debugging

      # Step 3: Check for Dependency Vulnerabilities with Snyk
      - name: Check for Dependency Vulnerabilities with Snyk
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: "--file=requirements.txt"  # Explicitly scan requirements.txt

      # Step 4: Check for Secrets in Code with TruffleHog
      - name: Scan for Secrets with TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./               # Explicitly reference the current directory
          scanArguments: "--regex --entropy=True --json"  # Use JSON output for better debugging

      # Step 5: Fail the build on any warnings/errors
      - name: Enforce Scan Results
        if: failure()  # Triggered if any step fails
        run: |
          echo "Security checks failed. Blocking the pull request."
          exit 1
