name: Security Checks

on:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: read
  id-token: write

jobs:
  security_scans:
    name: Security Scans
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit
      - name: Run Bandit SAST Scan
        id: bandit
        continue-on-error: true
        run: |
          echo "Running Bandit SAST analysis..."
          bandit -r . -f json -o bandit-report.json

      - name: Check for Dependency Vulnerabilities with Snyk
        id: snyk
        continue-on-error: true
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: "--file=requirements.txt"

      - name: Run TruffleHog v3 Scan for Secrets
        id: trufflehog
        continue-on-error: true
        run: |
          pip install trufflehog
          trufflehog filesystem --json . > trufflehog-results.json

      - name: Summarize Scan Results
        run: |
          echo "Summarizing results from all scans..."
          echo "Bandit result: ${{ steps.bandit.outcome }}"
          echo "Snyk result: ${{ steps.snyk.outcome }}"
          echo "TruffleHog result: ${{ steps.trufflehog.outcome }}"
          if [[ "${{ steps.bandit.outcome }}" == "failure" || "${{ steps.snyk.outcome }}" == "failure" || "${{ steps.trufflehog.outcome }}" == "failure" ]]; then
            echo "One or more security scans failed. Blocking the pull request."
            exit 1
